// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fchucoljvclbjsoseakj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjaHVjb2xqdmNsYmpzb3NlYWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODgxNTEsImV4cCI6MjA2NjE2NDE1MX0.F39ar_JY2qAEhDoFcC24JpqjVRBon2GkqW0tMokdjuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);